name: jaya_propertiy
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  either_dart: ^1.0.0
  email_validator: ^2.1.17
  fl_chart: ^0.65.0
  floating_bottom_bar: ^0.0.2
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  introduction_screen: ^3.1.12
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.0+4
  logger: ^2.0.2+1
  presentation_displays: ^1.0.0
  syncfusion_flutter_charts: ^24.1.45+2
  table_calendar: ^3.0.9
  flutter_svg: ^2.0.10+1
  flutter_carousel_widget: ^2.2.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  print_bluetooth_thermal: ^1.1.0
  esc_pos_utils_plus: ^2.0.2
  # esc_pos_utils: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/icons/
    - assets/icons/svg/
    # - assets/translations/